name:                PlayYouAHaskell
version:             0.1.0.0
github:              andreasMazur/PlayYouAHaskell
license:             MIT
author:              Andreas Mazur
maintainer:          Andreas Mazur
copyright:           2023 Andreas Mazur

extra-source-files:
- README.md
- ChangeLog.md


# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/andreasMazur/PlayYouAHaskell#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- array
- mtl
- parsec
- directory
- linear

library:
  source-dirs: src

executables:
  PlayYouAHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PlayYouAHaskell

tests:
  PlayYouAHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PlayYouAHaskell
